project:
  type: website
  output-dir: _site-public
  render:
    - index.qmd

website:
  title: "吉田山 植樹木マップ"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
